"""The two playbooks, and the prompts that invoke them.

A playbook is a procedure stored once in Devin and reused by every session, which
is what keeps results comparable across runs. If every prompt were bespoke, the
outcome mix would be noise.

Two playbooks because triage and remediation are different jobs with different
success conditions. Triage succeeds by reaching a defensible decision, including
"do nothing". Remediation succeeds by making a change that the project's own
tests accept — or by stopping when a guardrail says it should.
"""

from __future__ import annotations

from .models import Finding

TRIAGE_TITLE = "Triage an engineering-debt finding (Superset)"

TRIAGE_BODY = """\
You are triaging a finding on the Apache Superset codebase. Your job is to decide
what it deserves. You are not fixing anything in this session.

**"Do nothing" is a legitimate and valued outcome.** An hour saved dismissing a
false positive is worth as much as an hour saved landing a fix. Do not reach for
`remediate` because it feels more useful.

## Procedure

1. Read `AGENTS.md` and `SECURITY.md` in the repository root first. They define
   how this project expects automated tooling to behave, and they are binding here.

2. Independently verify each claim in the issue. Do not take the scanner's word
   for anything. Check the files, the versions, the referenced PRs and issues.
   If a claim is wrong, record it in `contradicted_evidence` — that is a useful
   result, not a criticism you should soften.

3. Answer the issue's "Open questions for triage" section specifically.

4. Read the "Do not" section. Those prohibitions are binding. If the only way to
   resolve the finding violates one, the answer is `decline_not_actionable` or
   `escalate_to_human`, and you should say which prohibition applies and why.

5. Assess blast radius by looking at what actually imports or depends on the code
   in question — not by guessing from the file count in the issue.

6. Decide:
   - `remediate` — real, actionable, and the change is worth making now
   - `decline_not_actionable` — no change is the correct engineering answer
   - `blocked_upstream` — cannot proceed until something external changes. Name
     the specific package, PR, issue or release. "The ecosystem" is not a blocker.
   - `escalate_to_human` — needs a judgement outside your remit. Say what a human
     must decide, and what you would recommend.

## On security findings

`AGENTS.md` requires that any automated security finding name the SECURITY.md
role-and-capability row it believes is violated, and the principal the attacker
is assumed to hold. It states that findings which cannot identify both should be
filed as questions, not vulnerabilities.

If you cannot name both, the correct decision is `decline_not_actionable`, with
reasoning explaining that the finding does not meet the project's own bar.

## Calibration

- Prefer `low` confidence with honest reasoning over a confident guess.
- A suppression that exists usually exists for a reason. Evidence that its stated
  condition has cleared means the upgrade is worth *retrying*, not that it is safe.
- Where a previous attempt was reverted, find out why before deciding.
"""


REMEDIATION_TITLE = "Remediate a finding in Apache Superset"

REMEDIATION_BODY = """\
You are making a change to the Apache Superset codebase, triaged as worth doing.

## Before you change anything

1. Read `AGENTS.md`. It is binding, and it describes active migrations you must
   not work against.
2. Read the issue's "Do not" section. Those prohibitions override the goal. If
   completing the task requires violating one, stop and report
   `abandoned_on_guardrail` naming the prohibition. That is a success, not a
   failure, and it is preferred over a change that satisfies the letter of the
   issue while doing the wrong thing.
3. Read the acceptance criteria. They are the definition of done.

## Repository-specific rules

- `requirements/*.txt` are generated by `uv pip compile`. **Never hand-edit them.**
  Change `requirements/*.in` or `pyproject.toml` and regenerate.
- Python unit tests run without a database:
  `pytest ./tests/common ./tests/unit_tests`
  Integration and e2e tests need Docker services; do not attempt them.
- Frontend tests: `npm run test -- <path>` from `superset-frontend`.
- Run `pre-commit run` on the files you changed before pushing. It matches CI.
- New files need the Apache licence header.
- PR titles follow Conventional Commits. Use `.github/PULL_REQUEST_TEMPLATE.md`.

## Verification is the deliverable

A change you cannot demonstrate is correct is not finished.

- Run the actual commands and record them verbatim in `verification.commands_run`.
- If a test fails, determine whether your change caused it or whether it already
  fails on the base branch. Say which.
- **Where the acceptance criteria ask for something you cannot verify in this
  environment, say so in `verification.unverifiable`.** An admitted gap is worth
  far more than an unverified claim. Passing unit tests is not evidence that a
  runtime failure is fixed.
- If you made a change but cannot show it correct, report `failed_verification`
  rather than opening a PR that looks finished.

## Scope

Change only what the issue asks for. Do not fix unrelated problems you notice,
do not reformat untouched files, and do not upgrade adjacent dependencies. If you
find something else worth doing, put it in `follow_up_required`.
"""


# ------------------------------------------------------------------ prompts

def triage_prompt(finding: Finding, issue_number: int | None, repo: str) -> str:
    guardrails = (
        "\n".join(f"- {g}" for g in finding.guardrails)
        if finding.guardrails else "- (none stated)"
    )
    questions = (
        "\n".join(f"- {q}" for q in finding.open_questions)
        if finding.open_questions else "- (none stated)"
    )
    evidence = "\n".join(
        f"- {e.claim}: {e.value}  [source: {e.source}]" for e in finding.evidence
    )
    issue_ref = f"\nTracking issue: {repo}#{issue_number}" if issue_number else ""

    return f"""\
Triage this finding on @{repo}. Decide what it deserves. Do not make any code
change in this session.
{issue_ref}

## {finding.title}

{finding.summary}

### Evidence supplied by the scanner — verify each independently
{evidence}

### Open questions you must answer
{questions}

### Do not
{guardrails}

Return your decision via structured output. `decline_not_actionable` is a valid
and valued result.
"""


def remediation_prompt(finding: Finding, issue_number: int | None, repo: str,
                       triage_reasoning: str = "",
                       extra: str = "") -> str:
    guardrails = (
        "\n".join(f"- {g}" for g in finding.guardrails)
        if finding.guardrails else "- (none stated)"
    )
    acceptance = (
        "\n".join(f"{i}. {a}" for i, a in enumerate(finding.acceptance, 1))
        if finding.acceptance else "(see the issue)"
    )
    paths = "\n".join(f"- {p}" for p in finding.paths) if finding.paths else "- (not scoped)"

    triage_block = (
        f"\n### Why triage decided to proceed\n\n{triage_reasoning}\n"
        if triage_reasoning else ""
    )
    extra_block = f"\n### Additional context from triage\n\n{extra}\n" if extra else ""
    close = (
        f"\n\nOpen a pull request against @{repo} that closes #{issue_number}."
        if issue_number else ""
    )

    return f"""\
Remediate this finding on @{repo}.

## {finding.title}

{finding.summary}
{triage_block}{extra_block}
### Files in scope
{paths}

### Do not
{guardrails}

### Acceptance criteria
{acceptance}
{close}

Report the outcome via structured output, including the exact verification
commands you ran and anything you could not verify.
"""
